---
- name: Run Second Playbook
  hosts: all
  become: true
  vars:
     - packages:
       - wget
       - curl
       - htop
  tasks:
      - name: create a user 
        ansible.builtin.user:
          name: devops-ansible
          group: sudo
          createhome: yes       
          home: /home/devops-ansible
 
      - name: Install Required Packages
        apt:
           pkg: "{{ packages }}"
           state: latest
           update_cache: yes
